name: kyc_app
description: "KYC App by Softmintindia Pvt. Ltd."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  logger: ^2.0.2+1
  device_info_plus: ^9.1.2
  pinput: ^3.0.1
  dropdown_search: ^5.0.6
  searchable_paginated_dropdown: ^1.2.0
  permission_handler: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logo/